fix: Linter

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -16,11 +16,11 @@ release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION"
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 #  Extract contents of tar.gz file into the download directory if needed.
- if [[ "$(uname | tr '[:upper:]' '[:lower:]')" =~ darwin* ]]; then
-   tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
-   # Remove the tar.gz file since we don't need to keep it
-   rm "$release_file"
+if [[ "$(uname | tr '[:upper:]' '[:lower:]')" =~ darwin* ]]; then
+  tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+  # Remove the tar.gz file since we don't need to keep it
+  rm "$release_file"
 else
-   # Linux versions need execution permssions.
-   chmod +x "$release_file"
- fi
+  # Linux versions need execution permssions.
+  chmod +x "$release_file"
+fi
