ci: Strip components again deleting the binary

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -18,7 +18,7 @@ download_release "$ASDF_INSTALL_VERSION" "$release_file"
 #  Extract contents of tar.gz file into the download directory if needed.
 if [[ "$(uname | tr '[:upper:]' '[:lower:]')" =~ darwin* ]]; then
   echo "* OSX versions are compressed, extracting them in $ASDF_DOWNLOAD_PATH"
-  tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+  tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
   # Remove the tar.gz file since we don't need to keep it
   rm "$release_file"
 fi
